# Generated by Django 2.1 on 2019-07-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='technology_used',
            field=models.CharField(default='tech', max_length=15),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
