# Generated by Django 2.1 on 2019-07-11 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myworks', '0002_auto_20190705_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='project name')),
                ('project_url', models.URLField(max_length=100)),
                ('project_repository', models.URLField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('technology_used', models.CharField(default='tech  ', max_length=15)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioModel',
        ),
    ]
