# Generated by Django 2.1 on 2019-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworks', '0003_auto_20190711_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.FilePathField(blank=True, path='/img'),
        ),
    ]
