# Generated by Django 2.1 on 2019-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworks', '0004_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
