# Generated by Django 2.1 on 2019-07-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myworks', '0006_auto_20190712_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
