# Generated by Django 2.1 on 2019-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworks', '0008_auto_20190713_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technology_used',
            field=models.CharField(max_length=15, verbose_name='technology'),
        ),
    ]
